apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin-2
  namespace: applications
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-2
  namespace: applications
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8087
    protocol: TCP
  selector:
    app: httpbin-2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-2
  namespace: applications
spec:
  hosts:
  - httpbin-2.applications.svc.cluster.local
  http:
  - name: primary
    route:
    - destination:
        host: httpbin-2
        subset: v1
        port:
          number: 8000
      weight: 100
    - destination:
        host: httpbin-2
        subset: v2
        port:
          number: 8000
      weight: 0
  - name: sandbox
    route:
      - destination:
          host: httpbin-2
          subset: sandbox
          port:
            number: 8000
        weight: 0
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: httpbin-2
  namespace: applications
spec:
  replicas: 5
  strategy:
    # blueGreen:
    #   activeService: httpbin-2
    #   previewService: httpbin-2-canary
    #   autoPromotionEnabled: true
    canary:
      # dynamicStableScale: true
      # abortScaleDownDelaySeconds: 600
      # maxSurge: "100%"
      # maxUnavailable: "10%" 
      # canaryService: httpbin-2-canary
      # stableService: httpbin-2
      trafficRouting:
        managedRoutes:
          - name: set-header-1
        istio:
          virtualServices:
          - name: httpbin-2 # At least one virtualService is required
            routes:
            - primary # At least one route is required
          destinationRule:
            name: httpbin-2
            canarySubsetName: v2
            stableSubsetName: v1
      steps:
      - setCanaryScale:
          replicas: 5
      - pause: { duration: 3m }
      - setWeight: 100
  # revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: httpbin-2
  template:
    metadata:
      labels:
        app: httpbin-2
        version: 1.0.12
        istio-injection: enabled
    spec:
      containers:
      - name: httpbin-2
        image: docker.io/lsantana/application:1.0.12
        # command: ["./cmd/app/1"]
        ports:
        - name: http
          containerPort: 8087
          protocol: TCP
        env:
        - name: VERSION
          value: 1.0.12
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: httpbin-2
  namespace: applications
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: httpbin-2
    
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-2
  namespace: applications
spec:
  host: httpbin-2.applications.svc.cluster.local
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-2-sandbox
  namespace: applications
spec:
  host: httpbin-2.applications.svc.cluster.local
  subsets:
  - labels:
      version: sandbox
    name: sandbox