---
apiVersion: v1
kind: Service
metadata:
  name: app4-{{ $.Values.DEPLOYMENT.ENV_COLOR }}
  labels:
    app: app4-{{ $.Values.DEPLOYMENT.ENV_COLOR }}
    release: {{ $.Release.Name }}-{{ $.Values.DEPLOYMENT.ENV_COLOR }}
spec:
  ports:
    - name: http-app4-{{ $.Values.DEPLOYMENT.ENV_COLOR }}
      port: 80
      targetPort: app4-{{ $.Values.DEPLOYMENT.ENV_COLOR }}
      protocol: TCP
  selector:
    app: app4-{{ $.Values.DEPLOYMENT.ENV_COLOR }}
    release: {{ $.Release.Name }}-{{ $.Values.DEPLOYMENT.ENV_COLOR }}