---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  hosts:
    - {{ .Chart.Name }}
  http:
    - name: "{{ .Release.Name }}-delegate-route"
      route:
        - destination:
            host: {{ .Chart.Name }}
            subset: release
          weight: 100
          headers:
            response:
              add:
                release: release
        - destination:
            host: {{ .Chart.Name }}
            subset: canary
          weight: 0
          headers:
            response:
              add:
                release: canary