---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: {{ $.Values.name }}
      version: {{ $.Values.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.version }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
      - image: docker.io/lsantana/{{ .Values.name }}:{{ .Values.version }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}
        {{- if .Values.configurations }}
        env:
        {{- range $key, $value := .Values.configurations }}
        {{- if $value.secure }}
        - name: {{ $value.name | upper }}
          value: secret
        {{- else}}
        - name: {{ $value.name | upper }}
          value: {{ $value.value }}
        {{- end }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.port }}
