---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - name: {{ .Values.name }}
    port: 8000
    targetPort: {{ default 8080 .Values.port }}
  selector:
    app: {{ .Values.name }}
    version: {{ $.Values.version }}