---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    service: {{ .Release.Name }}
spec:
  ports:
  - name: http-v1-3
    port: 8000
    targetPort: 8087
  selector:
    app: {{ .Release.Name }}