---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
spec:
  host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
  - labels:
      version: release
    name: release
  - labels:
      version: canary
    name: canary