---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 5
  strategy:
    canary:
      trafficRouting:
        managedRoutes:
          - name: set-header-1
        istio:
          virtualServices:
          - name: {{ .Release.Name }} # At least one virtualService is required
            routes:
            - primary # At least one route is required
          destinationRule:
            name: {{ .Release.Name }}
            canarySubsetName: canary
            stableSubsetName: release
      steps:
      - setCanaryScale:
          replicas: 5
      - pause: { duration: 3m }
      - setWeight: 100
  # revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: {{ .Values.version }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: docker.io/lsantana/{{ .Values.name }}:{{ .Values.version }}
        # command: ["./cmd/app/1"]
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        {{- if .Values.configurations }}
        env:
        {{- range $key, $value := .Values.configurations }}
        {{- if $value.secure }}
        - name: {{ $value.name | upper }}
          value: secret
        {{- else}}
        - name: {{ $value.name | upper }}
          value: {{ $value.value }}
        {{- end }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            memory: 32Mi
            cpu: 5m