---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  http:
  - name: primary
    route:
    - destination:
        host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: release
        port:
          number: 8000
      weight: 100
    - destination:
        host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: canary
        port:
          number: 8000
      weight: 0
